<<<<<<< HEAD
// mod controllers
pub mod auth_controller;
pub mod cv_card_controller;
pub mod dashboard_controller;
pub mod gallery_controller;
pub mod home_controller;
pub mod kegiatan_controller;
pub mod kesbangpol_controller;
pub mod majelis_pertimbangan_controller;
pub mod pdp_controller;
pub mod pelaksana_controller;
pub mod pendaftaran_dppi_controller;
pub mod pendaftaran_dppi_controller_provinsi;
pub mod pengumuman_controller;
pub mod post_controller;
pub mod preview;
pub mod rating_controller;
pub mod regulasi_controller;
pub mod surat_rekomendasi_controller;
pub mod user_controller;
pub mod userpanel;
pub mod video_controller;
pub mod visitor_advanced_controller;
pub mod visitor_controller;
=======
// mod controllers
pub mod auth_controller;
pub mod cv_card_controller;
pub mod dashboard_controller;
pub mod gallery_controller;
pub mod home_controller;
pub mod kegiatan_controller;
pub mod kesbangpol_controller;
pub mod majelis_pertimbangan_controller;
pub mod pdp_controller;
pub mod pelaksana_controller;
pub mod pendaftaran_dppi_controller;
pub mod pendaftaran_dppi_controller_provinsi;
pub mod pengumuman_controller;
pub mod post_controller;
pub mod preview;
pub mod rating_controller;
pub mod regulasi_controller;
pub mod surat_rekomendasi_controller;
pub mod user_controller;
pub mod userpanel;
pub mod video_controller;
pub mod visitor_advanced_controller;
pub mod visitor_controller;
>>>>>>> 84a9b1b1877d3e277f4e3c4af63ae68d6cdc7179
